### ISSUE TITLE
Author name now appends "Going Linux Podcast"

### ISSUE THREAD

**Issue by lah7** [ubuntu-mate/ubuntu-mate-guide#24]
After an update to https://guide.ubuntu-mate.org, which uses a newer version of `pandoc`. The export now titles the author as:

    Larry Bushey Going Linux Podcast

Whereas it was previously just:

    Larry Bushey

Is this OK? Looks like it reads the affiliation orgname, which is "Going Linux Podcast".

**Comment by goinglinux** [comment]
The change is good with me.
