### ISSUE TITLE
A better way to create documentation

### ISSUE THREAD

**Issue by ojn** [ubuntu-mate/ubuntu-mate-guide#3]
Maybe Ubuntu Mate Guide could use Asciidoctor instead?

**Comment by goinglinux** [comment]
Is there a reason Asciidoctor to create the documentation in HTML5 would be superior to using the same documentation application (yelp) used for MATE Help? Yelp appears to be the standard for help documentation in Gnome/MATE.

**Comment by ojn** [comment]
The tooling is superior (you can find asciidoc addons for all modern text editors), much easier to write. Docbook is one of the main formats that it produces and yelp is fine with Docbook as I understood. I've been trying to use Pug to contribute to this manual since it's fairly easy to write and convert to mallard but it's still a huge pain compared to asciidoctor tools.

**Comment by goinglinux** [comment]
OK, I'll look into converting to the docbook format so that you (and others) can contribute.

**Comment by goinglinux** [comment]
@ojn I just finished converting everything to the docbook format. I have pushed the new files. You can see them over here: https://github.com/goinglinux/ubuntu-mate-guide

Just waiting for @flexiondotorg  to process the pull request.

**Comment by ojn** [comment]
Thanks Larry, DocBook at least has this [documentation](https://tdg.docbook.org/tdg/4.5/docbook.html). 
The problem is that it's still xml and terrible format for collaboration and source control.
 
I uploaded the human-readable version here: https://github.com/ojn/ubuntu-mate-guide/blob/master/index.adoc

it is still in early stages and needs alot of cleanup and corrections but once it's done should be suitable to produce PDF and website versions. 

For the web vesion one could use https://github.com/asciidoctor/asciidoctor-backends/tree/master/haml/html5

Maybe the same way Taiga is doing it:
https://github.com/taigaio/taiga-doc

- one could line up HTML and PDF creation with the Makefile

And actually I would still stress that asciidoc syntax is much much easier to write. 
I have not found any good open source tools for working with either DocBook, Mallard or other xml files. 

If one would write the guide entirely in asciidoctor the conversion would be as easy as:

`asciidoctor -b docbook45 index.adoc`

just put this in Makefile: 

```
docbook:
	asciidoctor -b docbook45 index.adoc
```
and then run:

`make docbook`

every each time.

**Comment by goinglinux** [comment]
As you can imagine @ojn, I have been busy with full-time work and preparing for the Ubuntu-MATE release. Although the 18.04 release will be in the docbook format, I have made some progress toward converting to the asciidoctor format so that we can collaborate using that tool. I've been experimenting with it and I agree it is much easier to read and to use that straight docbook xml. 

Getting exactly the same format with asciidoctor as with docbook appears to be possible but is taking some learning on my part. I expect that I should have the conversion completed sometime after the release of 18.04. At that time I'll change the README and we can use asciidoctor for updates to the documentation for 18.10 and beyond. Thanks again for the suggestion. We'll get there!

**Comment by ojn** [comment]
@goinglinux you have done an amazing job writing this! A worthy addition to an already awesome distro.

I forgot to say that I used https://github.com/asciidoctor/docbookrx/blob/master/README.adoc
- that tool isn't finished yet so it produces quite rough output, but still better than rewriting from scratch I guess. 
I have done some manual clean up (https://github.com/ojn/ubuntu-mate-guide/blob/master/index.adoc), but its still possibly missing some chunks of bulleted lists and stuff like that. I'm planning to create a web and pdf verisions for 18.04 - the formatting will probably not match the docbook version but it's fine with me and I don't think it's necessary that it is exactly the same dot to dot. 

@flexiondotorg I wonder if we can use this repo with github pages to host web and PDF versions of ubuntu mate guide 18.04 at https://ubuntu-mate.github.io ? https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

I think that html and pdf versions should be quite usefull to lure new users to UM.

**Comment by flexiondotorg** [comment]
I think I'm going to close this. The content is more important than the mark up. Let focus on the content :smiley:
